config/routes.rb
Rails.application.routes.draw do
#管理者用ルーティング
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
  end

#ユーザー用ルーティング
  devise_for :users
  scope module: :public do
    root to: "homes#top"
#    get 'homes/about' => "homes#about", as: "about"

    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
    end

    #↑onlyにしなくてよい可能性あり。要確認。
    resources :users, only: [:show, :edit, :update]

    #検索用ルーティング
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - miruzo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miruzo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/6b1c834d2a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

<!--仮記載-->
    <header class="bg-light sticky-top">
      <div class="container">

      <% if user_signed_in? %>
        <div class="row">
          <div class="col-md-3">
      <!--検索用部分テンプレートに変更-->
            <%= link_to new_post_path,class:"nav-link text-dark", data: {"turbolinks" => false} do%>
              <i class="fa-solid fa-camera"></i> 新規投稿
            <% end %>
          </div>

        <div class="col-md-8 offset-md-1">
          <div class="search_form">
            <%= form_with url: search_path, local: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.select :range, options_for_select([['User'], ['Post']]) %>
              <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
              <%= f.submit "検索", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>

      <% end %>
      </div>
    </header>


    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
      <div class="push"></div>
    </main>



    <footer>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
        <div class="container">
          <div class="row">
            <a class="navbar-brand " href="/">
                <span>miruzo</span>
            </a>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li>
                    <%= link_to posts_path,class:"nav-link text-light" do%>
                      <i class="fas fa-home"></i> ホーム
                    <% end %>
                  </li>
                  <li>
                    <%= link_to user_path(current_user.id),class:"nav-link text-light" do%>
                      <i class="fa-solid fa-users"></i> マイページ
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete,class:"nav-link text-light" do%>
                      <i class="fa-solid fa-right-from-bracket"></i> ログアウト
                    <% end %>
                  </li>

                <% else %>
                  <li>
                    <%= link_to new_user_registration_path,class:"nav-link text-light" do%>
                      <i class="fa-solid fa-user-plus"></i> 新規登録
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_session_path,class:"nav-link text-light" do%>
                      <i class="fa-solid fa-right-to-bracket"></i> ログイン
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>

          </div>
        </div>
      </nav>
    </footer>
  </body>
</html>